#### Numpy

In [2]:
import numpy as np
import time

In [8]:
#lets declare a size
size = 100000000

#create two lists
list1 = range(size)
list2 = range(size)

#create two numpy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

In [9]:
#calculate time for python list
start = time.time()
result1 = [(x+y) for x,y in zip(list1,list2)]
print('Time for python lists in msec : ',(time.time() - start))

#calculting for numpy array
start = time.time()
result2 = (arr1 + arr2)
print('Time for numpy array in msec : ',(time.time() - start))

Time for python lists in msec :  18.17294192314148
Time for numpy array in msec :  4.407986879348755


In [19]:
import numpy as np

In [3]:
#defining a numpy array
intarray = np.array([1,2,3,4.5,5],int)

In [7]:
intarray

array([1, 2, 3, 4, 5])

In [6]:
intarray[0]

1

In [5]:
intarray[:3]

array([1, 2, 3])

In [8]:
intarray2 = np.array([5,6],int)

In [9]:
#concatenating two arrays
print(np.concatenate((intarray,intarray2)))

[1 2 3 4 5 5 6]


In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
#floatarray
floatarray = np.array([[1,2,3],[4,5,6]])
floatarray

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
floatarray.dtype

dtype('int32')

In [12]:
floatarray.shape

(2, 3)

In [13]:
rangearray = np.array(range(10),int)
rangearray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#np.arange(-1,11,2)

array([-1,  1,  3,  5,  7,  9])

In [16]:
rangearray.shape

(10,)

In [17]:
#converting 1d array to 2darray
rangearray = rangearray.reshape(5,2)

In [18]:
rangearray

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### Operations

In [25]:
arr1 = np.array([[1,2],[3,4]], int)
print(arr1)
arr2 = np.array([[11,12],[13,14]], int)
arr2

[[1 2]
 [3 4]]


array([[11, 12],
       [13, 14]])

In [40]:
#adding
print('array1 + array2 : \n',(arr1 + arr2))

array1 + array2 : 
 [[12 14]
 [16 18]]


In [27]:
#multiplication
print('Multiplying : \n',(arr1*arr2))

Multiplying : 
 [[11 24]
 [39 56]]


In [28]:
#square
print('Square : \n',np.sqrt(arr1*arr2))

Square : 
 [[3.31662479 4.89897949]
 [6.244998   7.48331477]]


In [29]:
#standard deviation
print('Square : \n',np.std(arr1*arr2))

Square : 
 16.80029761641144


In [32]:
sample_array = np.array([range(5),range(5),range(15,20)])
sample_array

array([[ 0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [33]:
np.unique(sample_array)

array([ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19])

In [34]:
array1 = np.arange(start = 12, stop=240, step = 12)
array1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [35]:
#same
array1 = np.arange(12,240,12)
array1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [38]:
np.linspace(1,20,4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

#### Random Arrays

In [42]:
print("Random Array : \n",np.random.rand(5))

Random Array : 
 [0.75862864 0.21357295 0.21131156 0.9719656  0.13190176]


In [48]:
#random matrix
np.random.seed(10) #to maintain the repeatability
print("Random Array : \n",np.random.rand(5,4))

Random Array : 
 [[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]
 [0.72175532 0.29187607 0.91777412 0.71457578]]


In [49]:
# generating random nos between 0-10
np.random.rand(10)*10

array([5.42544368, 1.42170048, 3.7334076 , 6.74133615, 4.41833174,
       4.34013993, 6.17766978, 5.13138243, 6.50397182, 6.01038953])

In [50]:
# random array of integers in a range 0-9
#floor returns the int part of the array
randomarray = np.floor(np.random.rand(10)*10)
randomarray

array([8., 5., 9., 3., 0., 3., 1., 8., 0., 6.])

In [54]:
np.sort(randomarray)

array([0., 0., 1., 3., 3., 5., 6., 8., 8., 9.])

In [51]:
#further simplification
np.random.randint(0,10,(2,5))

array([[1, 4, 0, 8, 5],
       [4, 7, 8, 8, 2]])

In [53]:
#further simplification
np.random.randint(0,30,10)

array([22, 25, 17, 15, 12,  8, 10, 13, 25, 11])

#### Q1. How to extract all numbers between a given range

In [55]:
arr1 = np.arange(-50,50)
arr1

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38,
       -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25,
       -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49])

In [65]:
#method1
index = np.where((arr1 >= 15) & (arr1 <= 35) )
arr1[index]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35])

In [58]:
#method2
arr1[(arr1 >= 15) & (arr1 <= 35)]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35])

#### Q2. How to print only 3 decimal places in a python numpy array

In [73]:
np.random.random?

In [72]:
np.random.rand?

In [74]:
rand_arr = np.random.random([5,3])
rand_arr

array([[0.293, 0.064, 0.979],
       [0.34 , 0.495, 0.977],
       [0.441, 0.318, 0.52 ],
       [0.578, 0.854, 0.068],
       [0.465, 0.782, 0.719]])

In [60]:
#round off to 3 decimal places
np.set_printoptions(precision=3)
rand_arr

array([[0.903, 0.535, 0.59 ],
       [0.039, 0.357, 0.08 ],
       [0.305, 0.331, 0.774],
       [0.04 , 0.429, 0.315],
       [0.636, 0.346, 0.043]])

#### Q3. Hpw to replace all values greater than a given value or a cutoff

In [61]:
array1 = np.arange(start = 12, stop=240, step = 12)
array1

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [62]:
#method 1
output_array = np.clip(array1 ,a_min=50, a_max=200)
output_array

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 200, 200, 200])

In [ ]:
#np.where(condition,if true, if false)

In [68]:
np.where(array1 < 50, 50, array1)

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 204, 216, 228])

In [75]:
#method 2
np.where(array1 < 50, 50, np.where(array1 > 200, 200, array1))
#np.where(condition, true value, false value)

array([ 50,  50,  50,  50,  60,  72,  84,  96, 108, 120, 132, 144, 156,
       168, 180, 192, 200, 200, 200])

#### Q4. How to drop all missing values from a numpy array

In [90]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan,9])
a

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan,  9.])

In [87]:
np.isnan(a)

array([False, False, False,  True, False, False, False,  True, False])

In [88]:
a[np.isnan(a)]

array([nan, nan])

In [89]:
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7., 9.])

##### Q5. How to get the position of top n values in a numpy array

In [81]:
np.random.seed(100)
a = np.random.randint(0,50,5)
a

array([ 8, 24,  3, 39, 23])

In [82]:
a.argsort()

array([2, 0, 4, 1, 3], dtype=int64)

In [93]:
a.argsort()[-3:]

array([8, 3, 7], dtype=int64)

In [83]:
#acces all the top values
a[a.argsort()[-3:]]

array([23, 24, 39])

#### 6. Find the common and uncommon elements

In [97]:
arr1 = np.array(range(7))
arr2 = np.array(range(5,10))

In [98]:
# Print only the common numbers
# Print only the uncommon numbers
print(arr1)
print(arr2)

[0 1 2 3 4 5 6]
[5 6 7 8 9]


In [107]:
#common element
np.intersect1d(arr1,arr2)

array([5, 6])

In [109]:
# uncommon values
np.setdiff1d(np.union1d(arr1,arr2),np.intersect1d(arr1,arr2))

array([0, 1, 2, 3, 4, 7, 8, 9])

# Series

In [110]:
import pandas as pd

In [140]:
s1 = pd.Series(arr2,index=['a','b','c','d','e'])
s1

a    5
b    6
c    7
d    8
e    9
dtype: int32

In [122]:
s1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [123]:
s1.values

array([5, 6, 7, 8, 9])

In [119]:
type(s1)

pandas.core.series.Series

In [127]:
s1 = pd.Series(np.random.randint(1,6,100)) #no. of bedrroms

In [128]:
s2 = pd.Series(np.random.randint(1,3,100)) #no 0f bathrroms

In [130]:
s3 = pd.Series(np.random.randint(10000,90000,100)) # rent

In [134]:
housemkt = pd.concat([s1,s2,s3],axis=1)

In [136]:
housemkt

0  1      2
0   4  1  53903
1   3  1  18567
2   3  1  83676
3   4  2  37353
4   5  2  89109
.. .. ..    ...
95  4  1  15475
96  5  2  62999
97  3  1  70749
98  1  2  87355
99  2  1  66412

[100 rows x 3 columns]

In [135]:
type(housemkt)

pandas.core.frame.DataFrame

In [138]:
housemkt = housemkt.rename(columns = {0:'Bedrooms',
                          1:'Bathrooms',
                          2:'Rent/month'})

In [139]:
housemkt

Bedrooms  Bathrooms  Rent/month
0          4          1       53903
1          3          1       18567
2          3          1       83676
3          4          2       37353
4          5          2       89109
..       ...        ...         ...
95         4          1       15475
96         5          2       62999
97         3          1       70749
98         1          2       87355
99         2          1       66412

[100 rows x 3 columns]

In [143]:
df = pd.read_csv('C:/Users/skesh/Desktop/Data/Earthquakes.csv')
df

Date      Time  Latitude  Longitude        Type   Depth  \
0      01/02/1965  13:44:18   19.2460   145.6160  Earthquake  131.60   
1      01/04/1965  11:29:49    1.8630   127.3520  Earthquake   80.00   
2      01/05/1965  18:05:58  -20.5790  -173.9720  Earthquake   20.00   
3      01/08/1965  18:49:43  -59.0760   -23.5570  Earthquake   15.00   
4      01/09/1965  13:32:50   11.9380   126.4270  Earthquake   15.00   
...           ...       ...       ...        ...         ...     ...   
23407  12/28/2016  08:22:12   38.3917  -118.8941  Earthquake   12.30   
23408  12/28/2016  09:13:47   38.3777  -118.8957  Earthquake    8.80   
23409  12/28/2016  12:38:51   36.9179   140.4262  Earthquake   10.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake   79.00   
23411  12/30/2016  20:08:28   37.3973   141.4103  Earthquake   11.94   

       Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0              NaN                     NaN        6.0             MW  ...   
1              NaN                     NaN        5.8             MW  ...   
2              NaN                     NaN        6.2             MW  ...   
3              NaN                     NaN        5.8             MW  ...   
4              NaN                     NaN        5.8             MW  ...   
...            ...                     ...        ...            ...  ...   
23407          1.2                    40.0        5.6             ML  ...   
23408          2.0                    33.0        5.5             ML  ...   
23409          1.8                     NaN        5.9            MWW  ...   
23410          1.8                     NaN        6.3            MWW  ...   
23411          2.2                     NaN        5.5             MB  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                             NaN            NaN                  NaN   
1                             NaN            NaN                  NaN   
2                             NaN            NaN                  NaN   
3                             NaN            NaN                  NaN   
4                             NaN            NaN                  NaN   
...                           ...            ...                  ...   
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

      Location Source Magnitude Source     Status  
0              ISCGEM           ISCGEM  Automatic  
1              ISCGEM           ISCGEM  Automatic  
2              ISCGEM           ISCGEM  Automatic  
3              ISCGEM           ISCGEM  Automatic  
4              ISCGEM           ISCGEM  Automatic  
...               ...              ...        ...  
23407              NN               NN   Reviewed  
23408              NN               NN   Reviewed  
23409              US               US   Reviewed  
23410              US

In [145]:
#checcking the dimesnions
df.shape

(23412, 21)

In [146]:
#checking the nulls
df.isnull()

Date   Time  Latitude  Longitude   Type  Depth  Depth Error  \
0      False  False     False      False  False  False         True   
1      False  False     False      False  False  False         True   
2      False  False     False      False  False  False         True   
3      False  False     False      False  False  False         True   
4      False  False     False      False  False  False         True   
...      ...    ...       ...        ...    ...    ...          ...   
23407  False  False     False      False  False  False        False   
23408  False  False     False      False  False  False        False   
23409  False  False     False      False  False  False        False   
23410  False  False     False      False  False  False        False   
23411  False  False     False      False  False  False        False   

       Depth Seismic Stations  Magnitude  Magnitude Type  ...  \
0                        True      False           False  ...   
1                        True      False           False  ...   
2                        True      False           False  ...   
3                        True      False           False  ...   
4                        True      False           False  ...   
...                       ...        ...             ...  ...   
23407                   False      False           False  ...   
23408                   False      False           False  ...   
23409                    True      False           False  ...   
23410                    True      False           False  ...   
23411                    True      False           False  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                            True           True                 True   
1                            True           True                 True   
2                            True           True                 True   
3                            True           True                 True   
4                            True           True                 True   
...                           ...            ...                  ...   
23407                       False          False                False   
23408                       False          False                False   
23409                        True          False                False   
23410                        True          False                False   
23411                       False          False                False   

       Horizontal Error  Root Mean Square     ID  Source  Location Source  \
0                  True              True  False   False            False   
1                  True              True  False   False            False   
2                  True              True  False   False            False   
3                  True              True  False   False            False   
4                  True              True  False   False            False   
...                 ...               ...    ...     ...              ...   
23407              True             False  False   False            False   
23408              True             False  False   False            False   
23409             False             False  False   False            False   
23410             False             False  False   False            False   
23411             False             False  False   False            False   

       Magnitude Source  Status  
0                 False   False  
1                 False   False  
2                 False   False  
3                 False   False  
4                 False   False  
...                 ...     ...  
23407             False   False  
23408             False   False  
23409             False   False  
23410             False   False  
23411             False   False  

[23412 rows x 21 columns]

In [147]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [149]:
df.head(7)

Date      Time  Latitude  Longitude        Type  Depth  Depth Error  \
0  01/02/1965  13:44:18    19.246    145.616  Earthquake  131.6          NaN   
1  01/04/1965  11:29:49     1.863    127.352  Earthquake   80.0          NaN   
2  01/05/1965  18:05:58   -20.579   -173.972  Earthquake   20.0          NaN   
3  01/08/1965  18:49:43   -59.076    -23.557  Earthquake   15.0          NaN   
4  01/09/1965  13:32:50    11.938    126.427  Earthquake   15.0          NaN   
5  01/10/1965  13:36:32   -13.405    166.629  Earthquake   35.0          NaN   
6  01/12/1965  13:32:25    27.357     87.867  Earthquake   20.0          NaN   

   Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0                     NaN        6.0             MW  ...   
1                     NaN        5.8             MW  ...   
2                     NaN        6.2             MW  ...   
3                     NaN        5.8             MW  ...   
4                     NaN        5.8             MW  ...   
5                     NaN        6.7             MW  ...   
6                     NaN        5.9             MW  ...   

   Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                         NaN            NaN                  NaN   
1                         NaN            NaN                  NaN   
2                         NaN            NaN                  NaN   
3                         NaN            NaN                  NaN   
4                         NaN            NaN                  NaN   
5                         NaN            NaN                  NaN   
6                         NaN            NaN                  NaN   

   Horizontal Error  Root Mean Square            ID  Source Location Source  \
0               NaN               NaN  ISCGEM860706  ISCGEM          ISCGEM   
1               NaN               NaN  ISCGEM860737  ISCGEM          ISCGEM   
2               NaN               NaN  ISCGEM860762  ISCGEM          ISCGEM   
3               NaN               NaN  ISCGEM860856  ISCGEM          ISCGEM   
4               NaN               NaN  ISCGEM860890  ISCGEM          ISCGEM   
5               NaN               NaN  ISCGEM860922  ISCGEM          ISCGEM   
6               NaN               NaN  ISCGEM861007  ISCGEM          ISCGEM   

  Magnitude Source     Status  
0           ISCGEM  Automatic  
1           ISCGEM  Automatic  
2           ISCGEM  Automatic  
3           ISCGEM  Automatic  
4           ISCGEM  Automatic  
5           ISCGEM  Automatic  
6           ISCGEM  Automatic  

[7 rows x 21 columns]

In [150]:
df.tail(5)

Date      Time  Latitude  Longitude        Type  Depth  \
23407  12/28/2016  08:22:12   38.3917  -118.8941  Earthquake  12.30   
23408  12/28/2016  09:13:47   38.3777  -118.8957  Earthquake   8.80   
23409  12/28/2016  12:38:51   36.9179   140.4262  Earthquake  10.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake  79.00   
23411  12/30/2016  20:08:28   37.3973   141.4103  Earthquake  11.94   

       Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
23407          1.2                    40.0        5.6             ML  ...   
23408          2.0                    33.0        5.5             ML  ...   
23409          1.8                     NaN        5.9            MWW  ...   
23410          1.8                     NaN        6.3            MWW  ...   
23411          2.2                     NaN        5.5             MB  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
23407               NaN            0.1898  NN00570710     NN              NN   
23408               NaN            0.2187  NN00570744     NN              NN   
23409               4.8            1.5200  US10007NAF     US              US   
23410               6.0            1.4300  US10007NL0     US              US   
23411               4.5            0.9100  US10007NTD     US              US   

      Magnitude Source    Status  
23407               NN  Reviewed  
23408               NN  Reviewed  
23409               US  Reviewed  
23410               US  Reviewed  
23411               US  Reviewed  

[5 rows x 21 columns]

In [151]:
#selecting limited columns
df.columns

Index(['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Depth Error',
       'Depth Seismic Stations', 'Magnitude', 'Magnitude Type',
       'Magnitude Error', 'Magnitude Seismic Stations', 'Azimuthal Gap',
       'Horizontal Distance', 'Horizontal Error', 'Root Mean Square', 'ID',
       'Source', 'Location Source', 'Magnitude Source', 'Status'],
      dtype='object')

In [156]:
#single column
df['Horizontal Distance']
#df.Horizontal Distance

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
         ...  
23407    0.120
23408    0.129
23409    0.992
23410    3.553
23411    0.681
Name: Horizontal Distance, Length: 23412, dtype: float64

In [157]:
# selecting multiple columns
df[['Date', 'Time', 'Latitude', 'Longitude']]

Date      Time  Latitude  Longitude
0      01/02/1965  13:44:18   19.2460   145.6160
1      01/04/1965  11:29:49    1.8630   127.3520
2      01/05/1965  18:05:58  -20.5790  -173.9720
3      01/08/1965  18:49:43  -59.0760   -23.5570
4      01/09/1965  13:32:50   11.9380   126.4270
...           ...       ...       ...        ...
23407  12/28/2016  08:22:12   38.3917  -118.8941
23408  12/28/2016  09:13:47   38.3777  -118.8957
23409  12/28/2016  12:38:51   36.9179   140.4262
23410  12/29/2016  22:30:19   -9.0283   118.6639
23411  12/30/2016  20:08:28   37.3973   141.4103

[23412 rows x 4 columns]

In [162]:
#droppiong a column
df.drop(columns = 'Date',inplace = True)

In [163]:
df

Time  Latitude  Longitude        Type   Depth  Depth Error  \
0      13:44:18   19.2460   145.6160  Earthquake  131.60          NaN   
1      11:29:49    1.8630   127.3520  Earthquake   80.00          NaN   
2      18:05:58  -20.5790  -173.9720  Earthquake   20.00          NaN   
3      18:49:43  -59.0760   -23.5570  Earthquake   15.00          NaN   
4      13:32:50   11.9380   126.4270  Earthquake   15.00          NaN   
...         ...       ...        ...         ...     ...          ...   
23407  08:22:12   38.3917  -118.8941  Earthquake   12.30          1.2   
23408  09:13:47   38.3777  -118.8957  Earthquake    8.80          2.0   
23409  12:38:51   36.9179   140.4262  Earthquake   10.00          1.8   
23410  22:30:19   -9.0283   118.6639  Earthquake   79.00          1.8   
23411  20:08:28   37.3973   141.4103  Earthquake   11.94          2.2   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
0                         NaN        6.0             MW              NaN   
1                         NaN        5.8             MW              NaN   
2                         NaN        6.2             MW              NaN   
3                         NaN        5.8             MW              NaN   
4                         NaN        5.8             MW              NaN   
...                       ...        ...            ...              ...   
23407                    40.0        5.6             ML            0.320   
23408                    33.0        5.5             ML            0.260   
23409                     NaN        5.9            MWW              NaN   
23410                     NaN        6.3            MWW              NaN   
23411                     NaN        5.5             MB            0.029   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                             NaN            NaN                  NaN   
1                             NaN            NaN                  NaN   
2                             NaN            NaN                  NaN   
3                             NaN            NaN                  NaN   
4                             NaN            NaN                  NaN   
...                           ...            ...                  ...   
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

      Location Source Magnitude Source     Status  
0              ISCGEM           ISCGEM  Automatic  
1              ISCGEM           ISCGEM  Automatic  
2              ISCGEM           ISCGEM  Automatic  
3              ISCGEM           ISCGEM  Automatic  
4              ISCGEM           ISCGEM  Automatic  
...               ...              ...        ...  
23407              NN               NN   Reviewed  
23408              NN               NN   Reviewed  
23409              US               US   Reviewed  
23410              

In [167]:
df.describe()

Latitude     Longitude         Depth  Depth Error  \
count  23412.000000  23412.000000  23412.000000  4461.000000   
mean       1.679033     39.639961     70.767911     4.993115   
std       30.113183    125.511959    122.651898     4.875184   
min      -77.080000   -179.997000     -1.100000     0.000000   
25%      -18.653000    -76.349750     14.522500     1.800000   
50%       -3.568500    103.982000     33.000000     3.500000   
75%       26.190750    145.026250     54.000000     6.300000   
max       86.005000    179.998000    700.000000    91.295000   

       Depth Seismic Stations     Magnitude  Magnitude Error  \
count             7097.000000  23412.000000       327.000000   
mean               275.364098      5.882531         0.071820   
std                162.141631      0.423066         0.051466   
min                  0.000000      5.500000         0.000000   
25%                146.000000      5.600000         0.046000   
50%                255.000000      5.700000         0.059000   
75%                384.000000      6.000000         0.075500   
max                934.000000      9.100000         0.410000   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
count                 2564.000000    7299.000000          1604.000000   
mean                    48.944618      44.163532             3.992660   
std                     62.943106      32.141486             5.377262   
min                      0.000000       0.000000             0.004505   
25%                     10.000000      24.100000             0.968750   
50%                     28.000000      36.000000             2.319500   
75%                     66.000000      54.000000             4.724500   
max                    821.000000     360.000000            37.874000   

       Horizontal Error  Root Mean Square  
count       1156.000000      17352.000000  
mean           7.662759          1.022784  
std           10.430396          0.188545  
min            0.085000          0.000000  
25%            5.300000          0.900000  
50%            6.700000          1.000000  
75%            8.100000          1.130000  
max           99.000000          3.440000

In [165]:
df['Latitude'].max()

86.005

In [166]:
df['Latitude'].min()

-77.08

In [164]:
df['Latitude'].mean()

1.6790331197719317

In [168]:
#impute the null values
df["Magnitude Type"]

0         MW
1         MW
2         MW
3         MW
4         MW
        ... 
23407     ML
23408     ML
23409    MWW
23410    MWW
23411     MB
Name: Magnitude Type, Length: 23412, dtype: object

In [169]:
df["Magnitude Type"].unique()

array(['MW', 'ML', 'MH', 'MS', 'MB', 'MWC', 'MD', nan, 'MWB', 'MWW',
       'MWR'], dtype=object)

In [170]:
df["Magnitude Type"].mode()

0    MW
dtype: object

In [171]:
df["Magnitude Type"].mode()[0]

'MW'

In [172]:
#filling those 3 missing values with mode

df["Magnitude Type"].fillna(df["Magnitude Type"].mode()[0],inplace=True)

In [173]:
df.isnull().sum()

Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    0
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [174]:
#unique values
df["Magnitude Type"].unique()

array(['MW', 'ML', 'MH', 'MS', 'MB', 'MWC', 'MD', 'MWB', 'MWW', 'MWR'],
      dtype=object)

In [175]:
#count of unique values
df["Magnitude Type"].nunique()

10

In [176]:
df["Magnitude Type"].value_counts()

MW     7725
MWC    5669
MB     3761
MWB    2458
MWW    1983
MS     1702
ML       77
MWR      26
MD        6
MH        5
Name: Magnitude Type, dtype: int64

In [178]:
df["Magnitude Type"].value_counts(normalize=True)

MW     0.329959
MWC    0.242141
MB     0.160644
MWB    0.104989
MWW    0.084700
MS     0.072698
ML     0.003289
MWR    0.001111
MD     0.000256
MH     0.000214
Name: Magnitude Type, dtype: float64

In [181]:
#sorting a dataframe
df[[ 'Latitude', 'Longitude', 'Type', 'Depth']].sort_values(by='Latitude')

Latitude  Longitude        Type  Depth
21304   -77.080   -148.864  Earthquake   12.0
11457   -72.448    174.838  Earthquake   10.0
18716   -67.034    111.199  Earthquake   10.0
4237    -66.448    -82.584  Earthquake   33.0
5717    -65.721   -175.714  Earthquake   10.0
...         ...        ...         ...    ...
14288    85.686     86.034  Earthquake   10.0
14255    85.734     84.439  Earthquake   10.0
14294    85.735     84.906  Earthquake   10.0
2910     85.992     30.825  Earthquake   15.0
15812    86.005     31.595  Earthquake   10.0

[23412 rows x 4 columns]

In [184]:
df[[ 'Latitude', 'Longitude', 'Type', 'Depth']].sort_values(by='Latitude',ascending=False)

Latitude  Longitude        Type  Depth
15812    86.005     31.595  Earthquake   10.0
2910     85.992     30.825  Earthquake   15.0
14294    85.735     84.906  Earthquake   10.0
14255    85.734     84.439  Earthquake   10.0
14288    85.686     86.034  Earthquake   10.0
...         ...        ...         ...    ...
5717    -65.721   -175.714  Earthquake   10.0
4237    -66.448    -82.584  Earthquake   33.0
18716   -67.034    111.199  Earthquake   10.0
11457   -72.448    174.838  Earthquake   10.0
21304   -77.080   -148.864  Earthquake   12.0

[23412 rows x 4 columns]

In [185]:
#filtering dataframes
df[df['Magnitude Type']=="MD"]

Time   Latitude   Longitude        Type   Depth  Depth Error  \
5523   15:32:11  46.207333 -122.188000  Earthquake   1.510         0.56   
11371  13:34:35  45.035167 -122.606500  Earthquake  19.608         2.84   
11618  03:28:56  42.316167 -122.026667  Earthquake   8.560         0.93   
11620  05:45:35  42.357500 -122.058333  Earthquake   8.530         0.85   
14426  01:43:54  47.074000 -123.463667  Earthquake  40.014         0.06   
15320  18:54:33  47.149000 -122.726667  Earthquake  51.798         0.92   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
5523                     18.0        5.7             MD             0.08   
11371                    40.0        5.6             MD              NaN   
11618                   201.0        5.9             MD             0.02   
11620                   234.0        6.0             MD             0.02   
14426                    48.0        5.8             MD             0.05   
15320                    67.0        6.8             MD             0.03   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
5523                          1.0           62.0             0.008296   
11371                         2.0           67.0             0.206700   
11618                         3.0          129.0                  NaN   
11620                         3.0          128.0                  NaN   
14426                         6.0           85.0                  NaN   
15320                         0.0           31.0                  NaN   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
5523              0.682              0.22  UW10084803     UW              UW   
11371             0.934              0.39  UW10306313     UW              UW   
11618             0.441              0.09  UW10313718     UW              UW   
11620             0.400              0.08  UW10313838     UW              UW   
14426             0.085              0.21  UW10474303     UW              UW   
15320             0.517              0.20  UW10530748     UW              UW   

      Magnitude Source    Status  
5523                UW  Reviewed  
11371               UW  Reviewed  
11618               UW  Reviewed  
11620               UW  Reviewed  
14426               UW  Reviewed  
15320               UW  Reviewed

In [186]:
#operating on the filtered dataframe
df[df['Magnitude Type']=="MD"][['Time','Latitude']]

Time   Latitude
5523   15:32:11  46.207333
11371  13:34:35  45.035167
11618  03:28:56  42.316167
11620  05:45:35  42.357500
14426  01:43:54  47.074000
15320  18:54:33  47.149000

In [187]:
df[df['Magnitude Type']=="MD"]['Depth'].max()

51.798

In [192]:
#multiple filgters
df[(df['Type']=='Nuclear Explosion') & (df['Magnitude']>6)]

Time  Latitude  Longitude               Type  Depth  Depth Error  \
2797   01:22:58    49.986     78.853  Nuclear Explosion    0.0          NaN   
2859   06:59:54    73.302     55.161  Nuclear Explosion    0.0          NaN   
2897   06:59:57    70.779     54.177  Nuclear Explosion    0.0          NaN   
3218   09:59:55    73.366     55.094  Nuclear Explosion    0.0          NaN   
3286   04:59:57    70.817     54.063  Nuclear Explosion    0.0          NaN   
3661   08:59:56    70.843     53.690  Nuclear Explosion    0.0          NaN   
3663   11:59:57    73.351     55.078  Nuclear Explosion    0.0          NaN   
5198   02:56:58    49.918     78.915  Nuclear Explosion    0.0          NaN   
5234   03:56:57    49.901     78.959  Nuclear Explosion    0.0          NaN   
5248   02:51:57    49.971     79.010  Nuclear Explosion    0.0          NaN   
5388   04:56:58    49.964     78.827  Nuclear Explosion    0.0          NaN   
5635   02:42:39    49.976     78.889  Nuclear Explosion    0.0          NaN   
6061   03:43:14    49.909     78.873  Nuclear Explosion    0.0          NaN   
6177   03:23:05    49.889     78.931  Nuclear Explosion    0.0          NaN   
6230   01:17:14    49.995     78.856  Nuclear Explosion    0.0          NaN   
6363   03:37:13    49.928     78.869  Nuclear Explosion    0.0          NaN   
6613   02:36:44    49.906     78.981  Nuclear Explosion    0.0          NaN   
6774   01:55:05    49.921     78.907  Nuclear Explosion    0.0          NaN   
7109   01:09:11    49.891     78.963  Nuclear Explosion    0.0          NaN   
7244   01:50:11    49.949     78.834  Nuclear Explosion    0.0          NaN   
7322   03:55:03    49.957     78.862  Nuclear Explosion    0.0          NaN   
8457   01:17:08    49.928     78.829  Nuclear Explosion    0.0          NaN   
8531   04:59:58    41.584     88.737  Nuclear Explosion    0.0          NaN   
8561   00:53:05    49.913     78.735  Nuclear Explosion    0.0          NaN   
8795   03:21:05    49.989     78.844  Nuclear Explosion    0.0          NaN   
8808   03:05:05    49.864     78.758  Nuclear Explosion    0.0          NaN   
8877   03:05:06    49.954     78.910  Nuclear Explosion    0.0          NaN   
8952   01:33:06    49.917     78.945  Nuclear Explosion    0.0          NaN   
8989   00:57:07    49.928     78.769  Nuclear Explosion    0.0          NaN   
9166   03:59:57    49.833     78.808  Nuclear Explosion    0.0          NaN   
9327   03:57:07    49.924     78.831  Nuclear Explosion    0.0          NaN   
10126  04:59:58    41.564     88.770  Nuclear Explosion    0.0          NaN   
10907  04:59:58    41.604     88.813  Nuclear Explosion    0.0          NaN   
12450  04:05:58    41.603     88.820  Nuclear Explosion    0.0          NaN   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
2797                      NaN        6.3             MB              NaN   
2859                      NaN        6.8             MB              NaN   
2897                      NaN        6.9             MB              NaN   
3218                      NaN        6.4             MB              NaN   
3286                      NaN        6.7             MB              NaN   
3661                      NaN        6.7             MB              NaN   
3663                      NaN        6.5             MB              NaN   
5198                      NaN        6.3             MB              NaN   
5234                      NaN        6.1             MB              NaN   
5248                      NaN        6.1             MB              NaN   
5388                      NaN        6.1             MB              NaN   
5635                      NaN        6.2             MB              NaN   
6061                      NaN        6.2             MB              NaN   
6177                      NaN        6.1             MB              NaN   
6230                      NaN        6.1             MB              NaN   
6363                      NaN

In [193]:
df[(df['Type']=='Nuclear Explosion') & (df['Magnitude']>6) & (df['Latitude'] > 50)] # three filters

Time  Latitude  Longitude               Type  Depth  Depth Error  \
2859  06:59:54    73.302     55.161  Nuclear Explosion    0.0          NaN   
2897  06:59:57    70.779     54.177  Nuclear Explosion    0.0          NaN   
3218  09:59:55    73.366     55.094  Nuclear Explosion    0.0          NaN   
3286  04:59:57    70.817     54.063  Nuclear Explosion    0.0          NaN   
3661  08:59:56    70.843     53.690  Nuclear Explosion    0.0          NaN   
3663  11:59:57    73.351     55.078  Nuclear Explosion    0.0          NaN   

      Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
2859                     NaN        6.8             MB              NaN   
2897                     NaN        6.9             MB              NaN   
3218                     NaN        6.4             MB              NaN   
3286                     NaN        6.7             MB              NaN   
3661                     NaN        6.7             MB              NaN   
3663                     NaN        6.5             MB              NaN   

      Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
2859                         NaN            NaN                  NaN   
2897                         NaN            NaN                  NaN   
3218                         NaN            NaN                  NaN   
3286                         NaN            NaN                  NaN   
3661                         NaN            NaN                  NaN   
3663                         NaN            NaN                  NaN   

      Horizontal Error  Root Mean Square          ID Source Location Source  \
2859               NaN               NaN  USP00003DP     US              US   
2897               NaN               NaN  USP00003YA     US              US   
3218               NaN               NaN  USP00007UG     US              US   
3286               NaN               NaN  USP00008N6     US              US   
3661               NaN               NaN  USP0000D69     US              US   
3663               NaN               NaN  USP0000D7G     US              US   

     Magnitude Source    Status  
2859               US  Reviewed  
2897               US  Reviewed  
3218               US  Reviewed  
3286               US  Reviewed  
3661               US  Reviewed  
3663               US  Reviewed

In [194]:
df[(df['Type']=='Nuclear Explosion') & (df['Magnitude']>6)][df['Latitude']>50] # a filter is applied on the filtered dataframe

C:\Users\skesh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


Time  Latitude  Longitude               Type  Depth  Depth Error  \
2859  06:59:54    73.302     55.161  Nuclear Explosion    0.0          NaN   
2897  06:59:57    70.779     54.177  Nuclear Explosion    0.0          NaN   
3218  09:59:55    73.366     55.094  Nuclear Explosion    0.0          NaN   
3286  04:59:57    70.817     54.063  Nuclear Explosion    0.0          NaN   
3661  08:59:56    70.843     53.690  Nuclear Explosion    0.0          NaN   
3663  11:59:57    73.351     55.078  Nuclear Explosion    0.0          NaN   

      Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
2859                     NaN        6.8             MB              NaN   
2897                     NaN        6.9             MB              NaN   
3218                     NaN        6.4             MB              NaN   
3286                     NaN        6.7             MB              NaN   
3661                     NaN        6.7             MB              NaN   
3663                     NaN        6.5             MB              NaN   

      Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
2859                         NaN            NaN                  NaN   
2897                         NaN            NaN                  NaN   
3218                         NaN            NaN                  NaN   
3286                         NaN            NaN                  NaN   
3661                         NaN            NaN                  NaN   
3663                         NaN            NaN                  NaN   

      Horizontal Error  Root Mean Square          ID Source Location Source  \
2859               NaN               NaN  USP00003DP     US              US   
2897               NaN               NaN  USP00003YA     US              US   
3218               NaN               NaN  USP00007UG     US              US   
3286               NaN               NaN  USP00008N6     US              US   
3661               NaN               NaN  USP0000D69     US              US   
3663               NaN               NaN  USP0000D7G     US              US   

     Magnitude Source    Status  
2859               US  Reviewed  
2897               US  Reviewed  
3218               US  Reviewed  
3286               US  Reviewed  
3661               US  Reviewed  
3663               US  Reviewed

In [197]:
#Creating a new column
df['New Magnitude'] = df['Magnitude'] + 0.5

In [199]:
df[['Magnitude','New Magnitude']]

Magnitude  New Magnitude
0            6.0            6.5
1            5.8            6.3
2            6.2            6.7
3            5.8            6.3
4            5.8            6.3
...          ...            ...
23407        5.6            6.1
23408        5.5            6.0
23409        5.9            6.4
23410        6.3            6.8
23411        5.5            6.0

[23412 rows x 2 columns]

In [200]:
#classify earthquakes greater than 7 disaster, not a disaster
df['Is_Disaster'] = np.where(df['Magnitude'] > 7, 'Yes', "No")

In [203]:
df[df['Magnitude'] < 7 ]

Time  Latitude  Longitude        Type   Depth  Depth Error  \
0      13:44:18   19.2460   145.6160  Earthquake  131.60          NaN   
1      11:29:49    1.8630   127.3520  Earthquake   80.00          NaN   
2      18:05:58  -20.5790  -173.9720  Earthquake   20.00          NaN   
3      18:49:43  -59.0760   -23.5570  Earthquake   15.00          NaN   
4      13:32:50   11.9380   126.4270  Earthquake   15.00          NaN   
...         ...       ...        ...         ...     ...          ...   
23407  08:22:12   38.3917  -118.8941  Earthquake   12.30          1.2   
23408  09:13:47   38.3777  -118.8957  Earthquake    8.80          2.0   
23409  12:38:51   36.9179   140.4262  Earthquake   10.00          1.8   
23410  22:30:19   -9.0283   118.6639  Earthquake   79.00          1.8   
23411  20:08:28   37.3973   141.4103  Earthquake   11.94          2.2   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  ...  \
0                         NaN        6.0             MW              NaN  ...   
1                         NaN        5.8             MW              NaN  ...   
2                         NaN        6.2             MW              NaN  ...   
3                         NaN        5.8             MW              NaN  ...   
4                         NaN        5.8             MW              NaN  ...   
...                       ...        ...            ...              ...  ...   
23407                    40.0        5.6             ML            0.320  ...   
23408                    33.0        5.5             ML            0.260  ...   
23409                     NaN        5.9            MWW              NaN  ...   
23410                     NaN        6.3            MWW              NaN  ...   
23411                     NaN        5.5             MB            0.029  ...   

       Horizontal Distance  Horizontal Error  Root Mean Square            ID  \
0                      NaN               NaN               NaN  ISCGEM860706   
1                      NaN               NaN               NaN  ISCGEM860737   
2                      NaN               NaN               NaN  ISCGEM860762   
3                      NaN               NaN               NaN  ISCGEM860856   
4                      NaN               NaN               NaN  ISCGEM860890   
...                    ...               ...               ...           ...   
23407                0.120               NaN            0.1898    NN00570710   
23408                0.129               NaN            0.2187    NN00570744   
23409                0.992               4.8            1.5200    US10007NAF   
23410                3.553               6.0            1.4300    US10007NL0   
23411                0.681               4.5            0.9100    US10007NTD   

       Source Location Source Magnitude Source     Status New Magnitude  \
0      ISCGEM          ISCGEM           ISCGEM  Automatic           6.5   
1      ISCGEM          ISCGEM           ISCGEM  Automatic           6.3   
2      ISCGEM          ISCGEM           ISCGEM  Automatic           6.7   
3      ISCGEM          ISCGEM           ISCGEM  Automatic           6.3   
4      ISCGEM          ISCGEM           ISCGEM  Automatic           6.3   
...       ...             ...              ...        ...           ...   
23407      NN              NN               NN   Reviewed           6.1   
23408      NN              NN               NN   Reviewed           6.0   
23409      US              US               US   Reviewed           6.4   
23410      US              US               US   Reviewed           6.8   
23411      US              US               US   Reviewed           6.0   

      Is_Disaster  
0              No  
1              No  
2              No  
3              No  
4              No  
...           ...  
23407          No  
23408          No  
23409          No  
23410          No  
23411          No  

[22674 rows x 22 columns]

In [204]:
df['new col'] = 'value'

In [205]:
df

Time  Latitude  Longitude        Type   Depth  Depth Error  \
0      13:44:18   19.2460   145.6160  Earthquake  131.60          NaN   
1      11:29:49    1.8630   127.3520  Earthquake   80.00          NaN   
2      18:05:58  -20.5790  -173.9720  Earthquake   20.00          NaN   
3      18:49:43  -59.0760   -23.5570  Earthquake   15.00          NaN   
4      13:32:50   11.9380   126.4270  Earthquake   15.00          NaN   
...         ...       ...        ...         ...     ...          ...   
23407  08:22:12   38.3917  -118.8941  Earthquake   12.30          1.2   
23408  09:13:47   38.3777  -118.8957  Earthquake    8.80          2.0   
23409  12:38:51   36.9179   140.4262  Earthquake   10.00          1.8   
23410  22:30:19   -9.0283   118.6639  Earthquake   79.00          1.8   
23411  20:08:28   37.3973   141.4103  Earthquake   11.94          2.2   

       Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  ...  \
0                         NaN        6.0             MW              NaN  ...   
1                         NaN        5.8             MW              NaN  ...   
2                         NaN        6.2             MW              NaN  ...   
3                         NaN        5.8             MW              NaN  ...   
4                         NaN        5.8             MW              NaN  ...   
...                       ...        ...            ...              ...  ...   
23407                    40.0        5.6             ML            0.320  ...   
23408                    33.0        5.5             ML            0.260  ...   
23409                     NaN        5.9            MWW              NaN  ...   
23410                     NaN        6.3            MWW              NaN  ...   
23411                     NaN        5.5             MB            0.029  ...   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

       Location Source Magnitude Source     Status New Magnitude Is_Disaster  \
0               ISCGEM           ISCGEM  Automatic           6.5          No   
1               ISCGEM           ISCGEM  Automatic           6.3          No   
2               ISCGEM           ISCGEM  Automatic           6.7          No   
3               ISCGEM           ISCGEM  Automatic           6.3          No   
4               ISCGEM           ISCGEM  Automatic           6.3          No   
...                ...              ...        ...           ...         ...   
23407               NN               NN   Reviewed           6.1          No   
23408               NN               NN   Reviewed           6.0          No   
23409               US               US   Reviewed           6.4          No   
23410               US               US   Reviewed           6.8          No   
23411               US               US   Reviewed           6.0          No   

      new col  
0       value  
1       value  
2       value  
3       value  
4       value  
...       ...  
23407   value  
23408   value  
23409   value  
23410   value  
23411   value  

[23412 rows x 23 columns]